#!/bin/bash

if [ -d ".venv" ]; then rm -Rf .venv; fi
if [ -d "node_modules" ]; then rm -Rf node_modules; fi
if [ -d "yarn.lock" ]; then rm yarn.lock; fi
python3 -m venv .venv
.venv/bin/pip install --upgrade pip
.venv/bin/pip install -rrequirements.txt && .venv/bin/pip install -rapi/tests/requirements.txt
yarn